{% set version = "1.10.0" %}
{% set hash = "3714e3db8c51e43028e10ad7adffb9a36fc4aa5b1a363c2d0c4303dd1be59a7c" %}

package:
  name: flatbuffers
  version: {{ version }}

source:
  fn: flatbuffers-{{ version }}.tar.gz
  url: https://github.com/google/flatbuffers/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1002
  skip: true  # [win and vc<14]

requirements:
  build:
   - cmake
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
   - ninja

test:
  commands:
    - test -f $PREFIX/bin/flatc                                                     # [not win]
    - test -f $PREFIX/include/flatbuffers/flatbuffers.h                             # [not win]
    - if not exist %PREFIX%\\Library\\bin\\flatc.exe exit 1                         # [win]
    - if not exist %PREFIX%\\Library\\include\\flatbuffers\\flatbuffers.h exit 1    # [win]

about:
  home: http://google.github.io/flatbuffers/
  license: Apache 2.0
  summary: Memory Efficient Serialization Library

extra:
  recipe-maintainers:
    - wesm
    - msarahan
    - jakirkham
    - xhochy
