travis:
  secure:
    BINSTAR_TOKEN: GT1+niOwlLtFiQOhrgvG6c4USoOkWMOKSFsy7n8YLqrjgO8PrRvYn9OsNJkt/ydV/h0/uJoLaWyxbdiPFkSKYfL8ZWxkDA3G02LUvdEqDpaWMmZqDaAZqJoGAVIbyR2iyK52xgxbjh90rqJZDbfLGMH93i1h/pWv0R5ZuZgX6My3cA/cgvVtEQVOLh6fRxatXq23+FHuOv8fZurMMTd5DM8ytTBUReQ6MMlu4ySHtq2VIRhxs6P2vauZNe2wV9Jl+3HuNkoHbAXsMCmt0fy9muGgWR2rNIVPltthHPqai55f5xB7iVZHxBVhmxH7rIA1jQWzysvZgko29V5AGFH7sLt6o0/U/N6L/14r6tYL8TWWZbou4uiC2hqolzNR+KH2u2QWr9++ijC5+uq2z10eRwqe7VXMCLiCnpMKAkSLBWRi5nxLCSizo/Y/LKT8Y2PRXKvQHkZt6Rh8G2V596Xl4cqGXI47zvpHCbfD2rad+jEqj+QU9dUHk7AFGgvK2sThbdSDVXzIUSCjoU3S/MuaGmn/SHo4GY9JVYCtgwjbByDDvlVhBs8QulmLCWcXisQ9qEPjmnamDvVygZiLinUcjRXWbH7poJEKUfrKaWJ3SXAWfqAt3rcjPqTmTflT2WxFr3Tbs5oJemr5enjQ/rhYSoH89cCGIQGEf5andv78cms=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
