travis:
  secure:
    BINSTAR_TOKEN: Q/E6dcB68+dOWVMqcw1khvF3mu1ya+SUVAycSCa0XYsspzTviIqS6SYdRBKqCy5WH8RBl+o4JBcgh/Ld7uvbN3atqdMwuXjAaqsMjU6UcG39KFjCqpAvfDnE+VIBQsOsvUbfGeLtlvQlgrlSJ0Dvc6r59gomD2qezASZ+tLS4APORqKfr1bnNTBwMLN7eUpE8TFjp5B7bsHd3cTTU5q9u0dKf5Xt0q2gPVhr82NWN2kUHNz9fDpkL5JABIEjb6lmmN6bunG9Drp+LiOuCjEgf0wDAlueM0aWXGXaq1UCppV1LUw0rLPDry9v72PbX98rktZ2UL0dLApY7GlFFmFf2mAmel851ZU+htjryQKyE9SifdHbPwDeLlejAp5vDpAikrpA4XaxwnRS5PmSv+UNg2BlNa83T0NAFQT9OlhSRtMlYq6oI2N0airOU3caEC6OPhkLckiXvm8zQVsEz8dPM3RY4LVaBQD7oVw248Rn7HZQGu4YVQsvWLyzxcL0D26Nn5KlJirUM88gOUZI/Nv8c9xbtyP7Fj8iZDP7DttoiK96LUnFsMYfHCDd8veWU8MHxQZKCO/LyFwwRHVKYDGfjz5yX88ML53V8d1CLS/7G9ree8MVHVZ8XmkgMqHRUkUmbEADQmbe01pdM1m7qKkg+0NzzIS/PjBDmT0ge5zX264=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
